Fix missing event loop in `test_asyncio.py`
Fixes the following exception:

```
Traceback (most recent call last):
  File "/tmp/github.com/mtdcr/pysml/examples/./test_asyncio.py", line 63, in <module>
    main(argv[1])
    ~~~~^^^^^^^^^
  File "/tmp/github.com/mtdcr/pysml/examples/./test_asyncio.py", line 52, in main
    loop = asyncio.get_event_loop()
  File "/usr/lib64/python3.14/asyncio/events.py", line 715, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.
```

Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>